replicaCount: 2

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/gitops-eks-platform/sample-api
  tag: "dev-placeholder"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automount: false

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: <DEV_API_HOST>
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true

nodeSelector: {}
tolerations: []
affinity: {}
