replicaCount: 3

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/gitops-eks-platform/sample-api
  tag: "REPLACE_WITH_PROMOTED_IMAGE_SHA"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: <PROD_API_HOST>
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75
